name: Build Custom Kargo Image

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout repository
    - name: Set up Docker Buildx
      uses: actions/setup-buildx-action@v3
    - name: Log in to the Container registry
      uses: actions/docker-login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: actions/docker-build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/kargo:latest
          ghcr.io/${{ github.repository }}/kargo:${{ github.sha }}
    
